### PR TITLE
Fix vllm docker tensor paralllel

### PR DESCRIPTION
**Pull request by yunfeng-scale**
there's some weird version conflict with pydantic using ray

tested by creating a llama 2 13b model with 2 shards

### CODE REVIEW

**Review by seanshi-scale — CHANGES_REQUESTED** [review]
think we want to move out of `model-engine/` and delete it soon actually, since right now it's just a duplicate of `llm-engine` that isn't as up to date

**Comment by yunfeng-scale** [comment]
> think we want to move out of `model-engine/` and delete it soon actually, since right now it's just a duplicate of `llm-engine` that isn't as up to date

oh hmm, how did i change things in that folder

**Comment by yunfeng-scale** [comment]
> think we want to move out of `model-engine/` and delete it soon actually, since right now it's just a duplicate of `llm-engine` that isn't as up to date

wait this is indeed in model-engine. this folder is not models.

**Review by seanshi-scale — APPROVED** [review]
oh lol oops my bad

**Pull request merged**
